name: "Bug Report"
description: Describe the bug 
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: Describe the bug 
      

  
    - type: textarea
    attributes:
      label: Log
      description: Add Errors.log from script directory
    validations:
      required: true
